version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/dripanuc/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/dripanuc/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception


services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress 
    
    volumes:
      - wordpress:/var/www/html
    
    networks:
      - inception
    
    restart: always
    
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes allow to store in a persistent disk the content in a local disk
    #db_data is a volume created by docker directly
    volumes:
      - mariadb:/var/lib/mysql
    # in case of problem we restart automatically the container
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env
  
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  
  
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - inception
    restart: always
    env_file:
      - .env

  adminer:
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - inception

  website:
    container_name: website
    build: ./requirements/bonus/website/.
    image: website:42
    ports:
      - "3000:3000"
    networks:
      - inception
    restart: always
    
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor:42
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  

