version: "3.5"

volumes:
  db_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/dripanuc/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/dripanuc/data/wordpress
      o: bind

networks:
  backend:
    name: backend
  
  frontend:
    name: frontend


services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - wordpress 
    
    volumes:
      - wordpress_data:/var/www/html
    
    networks:
      - frontend
    
    restart: always
    
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    restart: always
    env_file:
      - .env

  